create table player
(
    id        bigint generated by default as identity
        primary key,
    password  varchar(255) not null,
    user_name varchar(255) not null
        constraint ukevhd0pq12hfcjvre179p23fs0
            unique
);

alter table player
    owner to postgres;

create table role
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255) not null
);

alter table role
    owner to postgres;

create table player_roles
(
    player_id bigint not null
        constraint fk8tarhjqjhisa9dfu2py30rfd0
            references player,
    role_id   bigint not null
        constraint fki8auseacmr2n4wc4a4od7gc3x
            references role,
    primary key (player_id, role_id)
);

alter table player_roles
    owner to postgres;

INSERT INTO player (user_name, password) VALUES ('dulat', '123');
